### ISSUE TITLE
Add a new category

### ISSUE THREAD

**Issue by Mayurmg** [zero-to-mastery/resources#680]
Request to add a new category for some famous questions and algorithms asked in interview questions related to data structures

**Comment by DarshGupta1910** [comment]
@Mayurmg there is no need to add DS-algo related resources in this repo because there are already repo's that have been made only for DS-algo resources interview preparation etc...
I'm listing a few of them for your reference 
1) https://github.com/sachuverma/DataStructures-Algorithms
2) https://github.com/coding-minutes/data-structures-algorithms-level-up-bootcamp
3) https://github.com/kunal-kushwaha/Competitive-Programming-Resources

I hope it helps.
